import Nav from '@/components/Nav'
import './globals.css'
import { Inter } from 'next/font/google'
import { Footer } from '@/sections'
import { Providers } from '@/store/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <Providers>

          <Nav />

          {children}

          <section className="bg-black padding-x padding-t pb-8">
            <Footer />
          </section>
        </Providers>

      </body>
    </html>
  )
}
